apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: loadtests.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: LoadTest
    listKind: LoadTestList
    plural: loadtests
    singular: loadtest
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
