apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testruns.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: TestRun
    listKind: TestRunList
    plural: testruns
    singular: testrun
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
